name: Orchestration

on:
    workflow_dispatch:
        inputs:
            log_output:
                description: Show output?
                type: boolean
                required: true
                default: false
            config_repo:
                description: ssh_config repository to use
                required: true
                default: unybak/ssh-config
            exec_repo:
                description: Runner repository to use
                required: true
                default: unybak/run
            code_repo:
                description: Code repository to use
                required: true
                default: unybak/unybak

env:
    GH_TOKEN: ${{ secrets.UNY_AUTO_PAT }}

jobs:
    orchestration:
        runs-on: ubuntu-latest
        steps:
            - name: Prepare workspace
              run: |
                  gh repo clone "${{ github.event.inputs.code_repo }}" code
                  gh repo clone "${{ github.event.inputs.config_repo }}" code/config

            - name: Run backup orchestration script
              working-directory: code
              run: |
                  log_output="${{ github.event.inputs.log_output }}"
                  export log_output
                  chmod +x orchestration.bash
                  ./orchestration.bash "${{ github.event.inputs.exec_repo }}" \
                    "${{ github.event.inputs.code_repo }}"
