name: Refresh rclone tokens

on:
    workflow_dispatch:
    # schedule:
    #     - cron: "15 8 */2 * *"

env:
    GH_TOKEN: ${{ secrets.UNY_AUTO_PAT }}
    RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}

jobs:
    refresh-rclone-tokens:
        runs-on: ubuntu-latest
        steps:
            - name: Prepare workspace
              run: gh repo clone unybak/unybak code

            - name: Run token refresh script
              working-directory: code
              run: |
                  chmod +x refresh-rclone-tokens.bash
                  ./refresh-rclone-tokens.bash \
                    --remote "OneDrive-m" \
                    --org "$(echo "$GITHUB_REPOSITORY" | grep -o "^[^/]*")"
